fm_elfinder:
    assets_path: /bo/img
    instances:
        default:
            locale: fr # Langue
            editor: ckeditor # Editeur utilisé
            fullscreen: true # Taille d'affichage
            theme: smoothness # Thème à utiliser
            connector:
                roots:
                    uploads:
                        show_hidden: false # Masque les fichiers cachés
                        driver: LocalFileSystem # Pilote des fichiers
                        path: bo/img # Chemin d'upload
                        upload_allow: [ 'image/png', 'image/jpg', 'image/jpeg' ] # Fichiers autorisés
                        upload_deny: [ 'all' ] # Fichiers interdits
                        upload_max_size: 2M # Taille maximum
